version: "3"

services:
  node:
    build: .
    container_name: node_app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
